# Generated by Django 4.1.1 on 2022-09-10 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('idAccesorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Accesorio',
                'verbose_name_plural': 'Accesorios',
            },
        ),
        migrations.CreateModel(
            name='CategoriaPeso',
            fields=[
                ('idCategoriaPeso', models.AutoField(primary_key=True, serialize=False)),
                ('categoriaPeso', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('idCategoriaProducto', models.AutoField(primary_key=True, serialize=False)),
                ('categoriaProducto', models.CharField(max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('estatura', models.CharField(blank=True, max_length=100, null=True)),
                ('peso', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('idInscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaIns', models.DateTimeField(auto_now_add=True)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrossFit.cliente')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('idMembresia', models.AutoField(primary_key=True, serialize=False)),
                ('membresia', models.CharField(blank=True, max_length=100, null=True)),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Membresia',
                'verbose_name_plural': 'Membresias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('categoriaProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrossFit.categoriaproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False)),
                ('pagodiario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrossFit.inscripcion')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrossFit.producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('horaIng', models.TimeField(auto_now=True)),
                ('horaSalida', models.TimeField(auto_now=True)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrossFit.cliente')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='idMembresia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrossFit.membresia'),
        ),
        migrations.CreateModel(
            name='CrossFit',
            fields=[
                ('idCrossFit', models.AutoField(primary_key=True, serialize=False)),
                ('idAccesorios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrossFit.accesorios')),
                ('idInscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrossFit.inscripcion')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrossFit.producto')),
            ],
            options={
                'verbose_name': 'CrossFit',
                'verbose_name_plural': 'CrossFit',
            },
        ),
        migrations.AddField(
            model_name='accesorios',
            name='categoriaPeso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrossFit.categoriapeso'),
        ),
    ]
